version: "3"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:4.1.3
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file: ".env"
    volumes:
      - neo4j_plugins:/var/lib/neo4j/plugins
      - neo4j_data:/var/lib/neo4j/data
      - neo4j_logs:/logs
      - neo4j_backup:/var/lib/neo4j/backup
      - ./cypher:/cypher:rw
    command: "neo4j"

volumes:
  neo4j_plugins:
  neo4j_data:
  neo4j_logs:
  neo4j_backup:
